name: Run wakatime-to-toggl everyday
on:
  schedule:
    - cron: 00 00 * * * # Everyday at 00:00 AM UTC. You can change it according to your timezone
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npx wakatime-to-toggl -w "$WAKATIME_API_KEY" -t "$TOGGL_API_KEY"
        env:
          TOGGL_API_KEY: '${{ secrets.TOGGL_API_KEY }}'
          WAKATIME_API_KEY: '${{ secrets.WAKATIME_API_KEY }}'
